- name: test of lookup
  hosts: localhost
  tasks:
    - name: get SHA of most recent commit
      debug: msg="{{ lookup('pipe', 'git rev-parse HEAD') }}"

    - name: get the current shell
      debug: msg="{{ lookup('env', 'SHELL') }}"

    - name: create random password
      debug: msg="{{ lookup('password', 'deploy-password.txt') }}"

    - name: output message from template
      debug: msg="{{ lookup('template', 'message.j2') }}"

    - name: hoge
      debug: msg="{{ lookup('csvfile', 'sue file=users.csv delimiter=, col=1') }}"
